config/routes.rb
Justincampbell::Application.routes.draw do
  root to: 'projects#index'

  get 'burritos' => 'pages#burritos'
  get 'hire' => 'pages#hire'

  get 'blog/:slug' => 'blog#show'

  # Handle legacy Tumblr URLs
  get 'post/:tumblr_id/:slug' => 'blog#show'

  # Handle legacy TIL URLs
  get 'til.atom', to: redirect('http://til.justincampbell.me/index.atom')
  get 'til', to: redirect('http://til.justincampbell.me')
  get 'til/:slug', to: redirect("http://til.justincampbell.me/%{slug}")

  get 'resume' => 'resume#index'

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create', as: :authenticate
  get 'sign_out' => 'sessions#destroy', as: :sign_out
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
    md_url = "https://raw.github.com/justincampbell/resume/master/JustinCampbell.md"
    @md = Rails.cache.fetch(md_url, expires_in: 1.week) {
      Faraday.get(md_url).body
    }

    respond_to do |format|
      format.html     { render :index, layout: nil }
      format.markdown { render text: @md }
      format.text     { render text: plaintext(:markdown => @md) }
    end
  end

  private

  def plaintext(options)
    text = options[:markdown]

    [
      [/^\#{1,2} +(.*)$/, "#{'\1'}\n"], # Replace heading levels 1 and 2 with just the text and a space on the next line
      [/^### +(.*)$/, "#{'\1'}"], # Replace heading level 3 with just the text
      [/^> +(.*)$/, '\1'], # Remove > block prefixes
      [/^(\s*)\* *(.*)$/, '\1- \2'], # Replace bullets with dashes
      [/--/, '-'], # Replace em dash with dash
      [/- \[(.*)\]\((.*)\)/, '- \1:'], # Replace links in a list with just the text and a semicolon
      [/\[(.*)\]\((.*)\)/, '\2'], # Replace other links with just the url
      [/\*\*(.*)\*\*/, '\1'], # Remove bold text
      [/mailto\:/, ''], # Remove mailto: uris
      [/http\:\/\//, ''], # Remove http: uris
      [/\n{2,}/, "\n\n"], # Remove any double-blank spaces
      [/\ +$/, ''], # Remove any whitespace at the end of a line
      [/^([A-Za-z.,\/\- ]+)\n(.+), ([A-Z]+)$/, '\1, \2, \3'], # Format company and city on one line
      [/\n\n-/, "\n-"] # Remove empty lines before a bulleted list
    ].each do |sub|
      text.gsub! sub.first, sub.last
    end

    text << "\n" unless text.last == "\n" # Ensure a newline exists at the end of the file

    text
  end

end

app/views/resume/index.html.erb
<html>
  <head>
    <style type="text/css">

      body {
        text-rendering: optimizeLegibility;
        background: white;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: #333;
      }

      h1 {
        font-family: 'Palatino Linotype', 'Book Antiqua', Palatino, serif;
        letter-spacing: -0.05em;
        font-size: 5em;
        margin: 0px;
        color: #444
      }

      h2, h3 {
        font-family: Helvetica, Arial, sans-serif;
        font-weight: normal;
      }

      h2 { text-indent: .25em; }
      h3 { text-indent: .5em; }

      blockquote {
        color: #666;
        border-left: 5px solid #CCC;
        padding-left: 10px;
      }

      #wrapper {
        width: 960px;
        margin: auto;
      }

      #formats {
        text-align: right;
        float: right;
      }

    </style>
    <%= render "analytics/google" %>
    <title>Justin Campbell</title>
  </head>
  <body>
    <div id="wrapper">
      <div id="formats">
        Also available in
        <%= link_to "Markdown", resume_path(format: :md) %>,
        <%= link_to "Plaintext", resume_path(format: :txt) %>,
        or as a
        <%= link_to "PDF", 'https://s3.amazonaws.com/justincampbell/JustinCampbell.pdf' %>.</br>
        View source for the
        <%= link_to "website", 'http://github.com/justincampbell/justincampbell.me' %>
        or
        <%= link_to "resume", 'http://github.com/justincampbell/resume' %>.
      </div>
      <%= markdown @md, add_header_levels: false %>
    </div>
  </body>
</html>